# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-28 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Password'), (1, 'Public Key')])),
                ('username', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('pubkey', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('sitecode', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Routers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=20)),
                ('credentials', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangolg.Credentials')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangolg.Locations')),
            ],
        ),
    ]
