# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 06:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangolg', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credentials',
            new_name='Credential',
        ),
        migrations.RenameModel(
            old_name='Locations',
            new_name='Location',
        ),
        migrations.RenameModel(
            old_name='Routers',
            new_name='Router',
        ),
    ]
