# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangolg', '0002_auto_20160729_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='router',
            name='hostname',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
