# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-29 22:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangolg', '0003_auto_20160729_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CommandMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_template', models.CharField(max_length=50)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangolg.Command')),
            ],
        ),
        migrations.CreateModel(
            name='Syntax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='credential',
            name='name',
            field=models.CharField(default='Default Credentials', max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(max_length=20),
        ),
        migrations.AddField(
            model_name='commandmap',
            name='syntax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangolg.Syntax'),
        ),
        migrations.AddField(
            model_name='router',
            name='syntax',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='djangolg.Syntax'),
        ),
    ]
